-
  branches:
    only:
      - master
  
  image: Visual Studio 2019
  version: 0.9.{build}
  configuration: Release

  install:
    - cmd: git submodule update --init
  
  before_build:
    - cmd: cd src
    - cmd: nuget restore

  build:
    project: src/OldRod.sln
    verbosity: minimal

  artifacts:
    - path: src/OldRod/bin/Release
-
  branches:
    only:
      - port-asmres-v4
  
  image: Visual Studio 2019
  version: 0.10.{build}
  configuration: Release

  install:
    - cmd: git submodule update --init
  
  before_build:
    - cmd: nuget restore

  build:
    project: OldRod.sln
    verbosity: minimal

  artifacts:
    - path: src/OldRod/bin/Release

